### ISSUE TITLE
Visualization Tool

### ISSUE THREAD

**Issue by shivangi-aneja** [dafei-qin/NFR_pytorch#2]
Hi,

Thank you so much for open-sourcing your work.
Which tool did you use to render meshes in the paper? The results look really nice.

**Comment by dafei-qin** [comment]
Hi! We use Eevee in Blender to render all the meshes. The rendering setup basically follows [this guide](https://research.siggraph.org/blog/guides/rendering-a-paper-figure-with-blender/) with some slight modifications of the materials.

**Comment by shivangi-aneja** [comment]
Ah, thank you so much for the link.
