### ISSUE TITLE
About ICT

### ISSUE THREAD

**Issue by JasonAnn** [dafei-qin/NFR_pytorch#4]
Hi, thanks for the nice work!  A problem occurs when I run test_user.py, which indicates that "No such file or directory: './data/ICT_live_100". What should I do to solve this?

**Comment by dafei-qin** [comment]
Please check whether you downloaded the data files via the google link and place them under the repo directory.

**Comment by JasonAnn** [comment]
> Please check whether you downloaded the data files via the google link and place them under the repo directory.

Thanks a lot! By the way, another problem occurs: "No such file or directory: './third_party/ICT-FaceKit/11089.th".

**Comment by JasonAnn** [comment]
> Please check whether you downloaded the data files via the google link and place them under the repo directory.

Thank you very much! By the way, another issue is arising: "No such file or directory: './third_party/ICT-FaceKit/11089.th".
